name: 'CI'

on:
    - 'push'
    - 'pull_request'
env:
  IS_GITHUB: 'true'
  XDEBUG_MODE: 'coverage'

jobs:
    phpunit:
        runs-on: 'ubuntu-latest'

        strategy:
            fail-fast: false
            matrix:
                php_version:
                    - '8.1.17'
                    - '8.2.4'

        steps:
            -
                uses: 'actions/checkout@v2'
            -
                name: 'Redis - 6379'
                uses: 'supercharge/redis-github-action@1.5.0'
                with:
                    redis-container-name: 'redis_url1'
                    redis-port: 6379
            -
                name: 'Redis - 6380'
                uses: 'supercharge/redis-github-action@1.5.0'
                with:
                    redis-container-name: 'redis_url2'
                    redis-port: 6380
            -
                name: 'Memcache - 11211'
                uses: 'niden/actions-memcached@v7'
            -
                name: 'Install PHP Packages'
                uses: 'php-actions/composer@v6'
                with:
                    version: '2.x'
                    php_version: '${{ matrix.php_version }}'
                    php_extensions: >-
                        apcu
                        memcache
                        memcached
                        pcov
                        pdo
                        pdo_sqlite
                        redis
            -
                name: 'Lint - phpcs'
                uses: 'php-actions/composer@v6'
                with:
                    version: '2.x'
                    php_version: '${{ matrix.php_version }}'
                    php_extensions: >-
                        apcu
                        memcache
                        memcached
                        pcov
                        pdo
                        pdo_sqlite
                        redis
                    command: 'run'
                    args: "lint:phpcs"
            -
                name: 'Test - Unit'
                uses: 'php-actions/composer@v6'
                with:
                    version: '2.x'
                    php_version: '${{ matrix.php_version }}'
                    php_extensions: >-
                        apcu
                        memcache
                        memcached
                        pcov
                        pdo
                        pdo_sqlite
                        redis
                    command: 'run'
                    args: "test:unit"
            -
                name: 'Test - Acceptance'
                uses: 'php-actions/composer@v6'
                with:
                    version: '2.x'
                    php_version: '${{ matrix.php_version }}'
                    php_extensions: >-
                        apcu
                        memcache
                        memcached
                        pcov
                        pdo
                        pdo_sqlite
                        redis
                    command: 'run'
                    args: "test:acceptance"
